name: CI
on:
  pull_request:
  push:
    branches: [ main ]
    tags: [ "*" ]

permissions:
  contents: read

jobs:
  lint:
    name: Lint
    permissions:
      contents: read
      pull-requests: read
    uses: ./.github/workflows/lint.yml
    with:
      linters: gomodtidy
